import os
from .base_agent import BaseAgent

# Load project constitution
CONSTITUTION_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "..", "Project_Docs", "PROJECT_INSTRUCTIONS.md")

class ReviewerAgent(BaseAgent):
    def __init__(self, model: str = "local-model"):
        # Load rules if available to bake into system prompt
        constitution_snippet = ""
        try:
            if os.path.exists(CONSTITUTION_PATH):
                with open(CONSTITUTION_PATH, 'r', encoding='utf-8') as f:
                    # Load a strict subset to save context window (first 2000 chars usually contains core rules)
                    constitution_snippet = f.read()[:2000]
        except Exception as e:
            pass

        super().__init__(
            name="Security Reviewer",
            role="Constitution Auditor",
            system_prompt=f"""You are the Swarm's Security Reviewer and Constitution Auditor. 
Your job is to read the code generated by the Coder Agent and ensure it strictly follows the NexusOS project rules.
Specifically check for:
1. No external API keys or cloud calls (must be local).
2. Proper error handling.
3. No hardcoded secrets.

PROJECT CONSTITUTION RULES TO ENFORCE:
{constitution_snippet}

If the code passes, reply with exactly 'APPROVED'. If it fails, explain clearly why and suggest fixes.""",
            model=model
        )

    async def execute_review(self, code: str, task_spec: str) -> str:
        """Review code against spec and constitution."""
        review_prompt = f"""
        TASK SPECIFICATION:
        {task_spec}
        
        CODE TO REVIEW:
        {code}
        
        Analyze this code critically. If it's perfect, output APPROVED. Otherwise provide a detailed critique.
        """
        return await self.execute(review_prompt)
