import axios from 'axios';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PROJECT_ROOT = path.resolve(__dirname, '../../');
const REPORTS_DIR = path.join(PROJECT_ROOT, 'Project_Docs', 'Reports');
const LLM_API = 'http://127.0.0.1:1234/v1/chat/completions';

if (!fs.existsSync(REPORTS_DIR)) fs.mkdirSync(REPORTS_DIR, { recursive: true });

// ─────────────────────────────────────────────
// Crisis Scenarios Bank
// ─────────────────────────────────────────────
const CRISES = [
    "A major competitor just released a clone of our product for half the price. Users are flooding Twitter with comparisons.",
    "Our main payment gateway (Stripe) is down globally. No user can make purchases or subscribe. Revenue is bleeding by $2,000/hour.",
    "A critical zero-day vulnerability was publicly disclosed affecting our Node.js version. Hackers are actively exploiting it in the wild.",
    "Our lead developer just resigned without notice, taking proprietary knowledge of the core algorithm with them.",
    "A viral TikTok video is exposing a major UX flaw in our product. 500K views in 2 hours and counting. Brand reputation tanking.",
    "Our MongoDB Atlas cluster hit its storage limit. The database is in read-only mode. No new users can register, no data can be saved.",
    "A government regulatory body just announced our product violates new data privacy laws. We have 72 hours to comply or face a $500K fine.",
    "Our CDN provider suffered a DDoS attack. All static assets (images, CSS, JS bundles) are unreachable. The entire frontend is broken.",
    "A disgruntled former employee leaked our entire source code on a public GitHub repo. It's been forked 200 times already.",
    "Our AI model started generating harmful/biased content that went viral. Media outlets are picking up the story. PR nightmare incoming."
];

// ─────────────────────────────────────────────
// Main Simulation
// ─────────────────────────────────────────────
async function runChaosCEO() {
    console.log('═══════════════════════════════════════════════');
    console.log('  🔥 VibeLab Chaos CEO — Crisis Simulator v1.0');
    console.log('═══════════════════════════════════════════════\n');

    // Pick a random crisis
    const crisis = CRISES[Math.floor(Math.random() * CRISES.length)];
    console.log(`🚨 CRISIS SELECTED:\n   "${crisis}"\n`);

    // Call LLM as CEO
    console.log('👔 [CEO] Activating AI Chief Executive Officer...\n');

    const ceoPrompt = `CRISIS ALERT: ${crisis}

As the AI CEO of a tech startup called "VibeLab" (an AI-powered research platform), generate an immediate 3-step emergency action plan.

For each step, provide:
1. **Action Title** — What to do
2. **Execution Details** — Exactly how to execute it (be specific, include names, tools, timelines)
3. **Expected Outcome** — What this achieves

Additionally:
- If a code change is needed (like an emergency discount banner, a maintenance page, a hotfix, a rate limiter, or a status notification), output the EXACT React JSX or HTML/CSS code ready to deploy.
- If a public statement is needed, draft the exact tweet/email text.
- If a business pivot is needed, outline the 48-hour survival roadmap.

Format: Use clear Markdown with headers, bullet points, and code blocks. Be decisive, specific, and aggressive — we are in crisis mode.`;

    try {
        const response = await axios.post(LLM_API, {
            model: 'qwen2.5-coder-7b-instruct',
            messages: [
                { role: 'system', content: 'You are a battle-hardened AI CEO with 20 years of crisis management experience. You are decisive, specific, and aggressive. Output actionable Markdown.' },
                { role: 'user', content: ceoPrompt }
            ],
            temperature: 0.5,
            max_tokens: 3000
        }, { timeout: 90000 });

        const ceoResponse = response.data?.choices?.[0]?.message?.content?.trim();

        if (!ceoResponse) {
            console.error('🛑 [CEO] Empty response from LLM.');
            return;
        }

        // Build the report
        const reportContent = `# 🚨 Crisis Resolution Report
> Generated: ${new Date().toISOString()}

## Crisis Scenario
> ${crisis}

---

## CEO Emergency Action Plan

${ceoResponse}

---

*This report was auto-generated by the VibeLab Chaos CEO simulator.*
*Review all recommendations before executing in production.*
`;

        // Save report
        const reportFileName = `CRISIS_RESOLUTION_${Date.now()}.md`;
        const reportPath = path.join(REPORTS_DIR, reportFileName);
        fs.writeFileSync(reportPath, reportContent, 'utf8');

        console.log('═══════════════════════════════════════════════');
        console.log(`  ✅ Chaos CEO simulation complete.`);
        console.log(`  📝 Report: Project_Docs/Reports/${reportFileName}`);
        console.log('═══════════════════════════════════════════════');

    } catch (err) {
        console.error(`\n💀 [CEO FATAL] LLM request failed: ${err.message}`);
    }
}

runChaosCEO();
