import fs from 'fs';
import path from 'path';
import axios from 'axios';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PROJECT_ROOT = path.resolve(__dirname, '../../');
const DRAFTS_DIR = path.join(PROJECT_ROOT, 'backend', '.vibelab_drafts');
const WALLET_FILE = path.join(PROJECT_ROOT, 'backend', 'ai_training', 'wallet_state.json');

// ─── Config (env-driven, no hardcoded keys) ───
const GITHUB_TOKEN = process.env.GITHUB_TOKEN || null;
const GITCOIN_API_KEY = process.env.GITCOIN_API_KEY || null;
const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY || null;
const ETHEREUM_RPC = process.env.ETHEREUM_RPC || 'http://127.0.0.1:8545'; // Local node or Infura
const WALLET_PRIVATE_KEY = process.env.VIBELAB_WALLET_KEY || null;
const AUTO_SPEND_THRESHOLD_USD = 10;

// ═══════════════════════════════════════════════
// 💰 Module 1: GitHub PR Submission
// ═══════════════════════════════════════════════

/**
 * Submit a patch as a Pull Request to GitHub.
 * Forks the repo, creates a branch, commits the fix, and opens a PR.
 */
export async function submitBountyPR(owner, repo, issueNumber, patchCode, commitMessage) {
    console.log(`\n📤 [FUNDER] Submitting PR for Issue #${issueNumber} to ${owner}/${repo}...`);

    if (!GITHUB_TOKEN) {
        console.warn('⚠️ [FUNDER] GITHUB_TOKEN not set. PR submission skipped (dry-run mode).');
        return {
            success: false,
            reason: 'GITHUB_TOKEN not configured',
            dryRun: true,
            wouldSubmit: { owner, repo, issueNumber, commitMessage }
        };
    }

    const headers = {
        'Authorization': `Bearer ${GITHUB_TOKEN}`,
        'Accept': 'application/vnd.github.v3+json',
        'User-Agent': 'VibeLab-BountyHunter/1.0'
    };

    try {
        // Step 1: Fork the repo (GitHub auto-handles if already forked)
        console.log('   🍴 Forking repository...');
        const forkRes = await axios.post(
            `https://api.github.com/repos/${owner}/${repo}/forks`,
            {},
            { headers, timeout: 30000 }
        );
        const forkOwner = forkRes.data.owner.login;
        const forkFullName = forkRes.data.full_name;
        console.log(`   ✅ Fork: ${forkFullName}`);

        // Step 2: Get the default branch's latest commit SHA
        const repoRes = await axios.get(
            `https://api.github.com/repos/${forkOwner}/${repo}`,
            { headers }
        );
        const defaultBranch = repoRes.data.default_branch;

        const refRes = await axios.get(
            `https://api.github.com/repos/${forkOwner}/${repo}/git/refs/heads/${defaultBranch}`,
            { headers }
        );
        const baseSHA = refRes.data.object.sha;

        // Step 3: Create a new branch
        const branchName = `vibelab-fix-${issueNumber}-${Date.now()}`;
        await axios.post(
            `https://api.github.com/repos/${forkOwner}/${repo}/git/refs`,
            { ref: `refs/heads/${branchName}`, sha: baseSHA },
            { headers }
        );
        console.log(`   🌿 Branch: ${branchName}`);

        // Step 4: Create the file with the patch
        const fileName = `vibelab_fix_issue_${issueNumber}.js`;
        const contentBase64 = Buffer.from(patchCode).toString('base64');

        await axios.put(
            `https://api.github.com/repos/${forkOwner}/${repo}/contents/${fileName}`,
            {
                message: commitMessage || `fix: resolve issue #${issueNumber} [VibeLab Auto-Bounty]`,
                content: contentBase64,
                branch: branchName
            },
            { headers }
        );
        console.log(`   📝 Committed: ${fileName}`);

        // Step 5: Open a Pull Request
        const prRes = await axios.post(
            `https://api.github.com/repos/${owner}/${repo}/pulls`,
            {
                title: `[VibeLab Auto-Fix] Issue #${issueNumber}`,
                head: `${forkOwner}:${branchName}`,
                base: defaultBranch,
                body: `## 🤖 Auto-Generated Fix by VibeLab Bounty Hunter\n\nThis PR addresses **Issue #${issueNumber}**.\n\n- Generated by local LLM\n- Verified via TDD Docker Sandbox (all tests passed)\n- Submitted automatically\n\n---\n*Powered by VibeLab Autonomous Agent System*`
            },
            { headers }
        );

        console.log(`   ✅ PR opened: ${prRes.data.html_url}`);
        return { success: true, prUrl: prRes.data.html_url, prNumber: prRes.data.number };

    } catch (err) {
        console.error(`   ❌ PR submission failed: ${err.response?.data?.message || err.message}`);
        return { success: false, error: err.message };
    }
}

// ═══════════════════════════════════════════════
// 💰 Module 2: Bounty Platform Integrations
// ═══════════════════════════════════════════════

/**
 * Claim a bounty on Gitcoin (skeleton — API subject to change).
 */
export async function claimGitcoinBounty(bountyId) {
    console.log(`\n🏆 [FUNDER] Claiming Gitcoin bounty: ${bountyId}...`);

    if (!GITCOIN_API_KEY) {
        console.warn('⚠️ [FUNDER] GITCOIN_API_KEY not set. Bounty claim skipped.');
        return { success: false, reason: 'GITCOIN_API_KEY not configured', dryRun: true };
    }

    try {
        // Gitcoin Grants API (skeleton — actual endpoints may differ)
        const res = await axios.post('https://gitcoin.co/api/v1/bounties/claim', {
            bounty_id: bountyId,
            worker_address: await getWalletAddress()
        }, {
            headers: { 'Authorization': `Bearer ${GITCOIN_API_KEY}` },
            timeout: 30000
        });

        console.log(`   ✅ Bounty claimed: ${res.data?.status || 'pending'}`);
        return { success: true, data: res.data };
    } catch (err) {
        console.error(`   ❌ Gitcoin claim failed: ${err.message}`);
        return { success: false, error: err.message };
    }
}

/**
 * Check available bounties on Replit Bounties (skeleton).
 */
export async function checkReplitBounties() {
    console.log('\n🔍 [FUNDER] Checking Replit Bounties...');

    try {
        // Replit Bounties API (hypothetical — Replit doesn't have a public bounties API yet)
        const res = await axios.get('https://replit.com/api/v1/bounties?status=open&sort=value', {
            headers: { 'User-Agent': 'VibeLab-Funder/1.0' },
            timeout: 15000
        });

        const bounties = res.data?.bounties || [];
        console.log(`   📋 Found ${bounties.length} open bounties`);
        return bounties;
    } catch (err) {
        console.warn(`   ⚠️ Replit Bounties API unavailable: ${err.message}`);
        return [];
    }
}

// ═══════════════════════════════════════════════
// 💰 Module 3: Web3 Wallet Integration
// ═══════════════════════════════════════════════

let ethersLib = null;

async function loadEthers() {
    if (ethersLib) return ethersLib;
    try {
        ethersLib = await import('ethers');
        return ethersLib;
    } catch (e) {
        console.warn('⚠️ [FUNDER] ethers.js not installed. Install with: npm install ethers');
        return null;
    }
}

/**
 * Get or create a wallet state file for tracking funds.
 */
function loadWalletState() {
    try {
        if (fs.existsSync(WALLET_FILE)) {
            return JSON.parse(fs.readFileSync(WALLET_FILE, 'utf8'));
        }
    } catch (e) { /* */ }

    const defaultState = {
        address: null,
        totalEarned: '0',
        totalSpent: '0',
        transactions: [],
        lastChecked: null
    };

    const dir = path.dirname(WALLET_FILE);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(WALLET_FILE, JSON.stringify(defaultState, null, 2), 'utf8');
    return defaultState;
}

function saveWalletState(state) {
    const dir = path.dirname(WALLET_FILE);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(WALLET_FILE, JSON.stringify(state, null, 2), 'utf8');
}

/**
 * Get the wallet address from the private key.
 */
export async function getWalletAddress() {
    const ethers = await loadEthers();
    if (!ethers || !WALLET_PRIVATE_KEY) {
        return loadWalletState().address || 'NOT_CONFIGURED';
    }

    try {
        const wallet = new ethers.Wallet(WALLET_PRIVATE_KEY);
        const state = loadWalletState();
        state.address = wallet.address;
        saveWalletState(state);
        return wallet.address;
    } catch (e) {
        return 'INVALID_KEY';
    }
}

/**
 * Check the wallet's ETH balance.
 */
export async function checkWalletBalance() {
    console.log('\n💳 [FUNDER] Checking wallet balance...');

    const ethers = await loadEthers();
    if (!ethers || !WALLET_PRIVATE_KEY) {
        console.warn('⚠️ [FUNDER] Wallet not configured. Set VIBELAB_WALLET_KEY env var.');
        return { eth: '0', usd: 0 };
    }

    try {
        const provider = new ethers.JsonRpcProvider(ETHEREUM_RPC);
        const wallet = new ethers.Wallet(WALLET_PRIVATE_KEY, provider);
        const balanceWei = await provider.getBalance(wallet.address);
        const balanceEth = ethers.formatEther(balanceWei);

        // Rough ETH→USD conversion (fetch live price in production)
        let ethPrice = 2000; // Fallback
        try {
            const priceRes = await axios.get('https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd', { timeout: 5000 });
            ethPrice = priceRes.data?.ethereum?.usd || 2000;
        } catch (e) { /* use fallback */ }

        const balanceUsd = parseFloat(balanceEth) * ethPrice;

        const state = loadWalletState();
        state.address = wallet.address;
        state.lastChecked = new Date().toISOString();
        saveWalletState(state);

        console.log(`   💰 Address: ${wallet.address}`);
        console.log(`   💰 Balance: ${parseFloat(balanceEth).toFixed(6)} ETH (~$${balanceUsd.toFixed(2)})`);

        return { eth: balanceEth, usd: balanceUsd, address: wallet.address };
    } catch (err) {
        console.error(`   ❌ Balance check failed: ${err.message}`);
        return { eth: '0', usd: 0, error: err.message };
    }
}

// ═══════════════════════════════════════════════
// 💰 Module 4: Auto-Purchase API Credits
// ═══════════════════════════════════════════════

/**
 * Automatically buy API credits/GPU time if wallet has enough funds.
 * Supports Stripe (for OpenAI/cloud GPU credits).
 */
export async function buyApiCredits() {
    console.log('\n🛒 [FUNDER] Evaluating auto-purchase of API credits...');

    const balance = await checkWalletBalance();

    if (balance.usd < AUTO_SPEND_THRESHOLD_USD) {
        console.log(`   ⏸️ Balance ($${balance.usd.toFixed(2)}) below threshold ($${AUTO_SPEND_THRESHOLD_USD}). Skipping.`);
        return { purchased: false, reason: 'Insufficient balance' };
    }

    console.log(`   ✅ Balance ($${balance.usd.toFixed(2)}) exceeds threshold. Initiating purchase...`);

    // ── Option A: Buy OpenAI API credits via Stripe ──
    if (STRIPE_SECRET_KEY) {
        try {
            const purchaseAmount = Math.min(balance.usd * 0.5, 50); // Spend max 50% or $50

            // Stripe Payment Intent (skeleton — requires valid Stripe setup)
            const stripeRes = await axios.post('https://api.stripe.com/v1/payment_intents',
                new URLSearchParams({
                    amount: Math.floor(purchaseAmount * 100), // cents
                    currency: 'usd',
                    description: 'VibeLab Auto-Purchase: Cloud GPU Credits',
                    'metadata[source]': 'vibelab-auto-funder',
                    'metadata[timestamp]': new Date().toISOString()
                }).toString(),
                {
                    headers: {
                        'Authorization': `Bearer ${STRIPE_SECRET_KEY}`,
                        'Content-Type': 'application/x-www-form-urlencoded'
                    },
                    timeout: 15000
                }
            );

            const state = loadWalletState();
            state.totalSpent = (parseFloat(state.totalSpent) + purchaseAmount).toString();
            state.transactions.push({
                type: 'purchase',
                amount: purchaseAmount,
                currency: 'USD',
                description: 'Cloud GPU Credits via Stripe',
                stripeId: stripeRes.data?.id,
                timestamp: new Date().toISOString()
            });
            saveWalletState(state);

            console.log(`   🛒 Purchase initiated: $${purchaseAmount.toFixed(2)} in GPU credits`);
            return { purchased: true, amount: purchaseAmount, stripeId: stripeRes.data?.id };

        } catch (err) {
            console.error(`   ❌ Stripe purchase failed: ${err.response?.data?.error?.message || err.message}`);
            return { purchased: false, error: err.message };
        }
    }

    console.log('   ⚠️ STRIPE_SECRET_KEY not set. Auto-purchase disabled.');
    return { purchased: false, reason: 'No payment gateway configured' };
}

// ═══════════════════════════════════════════════
// 💰 Module 5: Full Pipeline Orchestrator
// ═══════════════════════════════════════════════

/**
 * After a bounty patch is created, run the full monetization pipeline:
 * 1. Submit PR to GitHub
 * 2. Claim the bounty on the platform
 * 3. Check wallet for incoming funds
 * 4. Auto-purchase API credits if threshold met
 */
export async function runFundingPipeline(owner, repo, issueNumber, patchCode) {
    console.log('═══════════════════════════════════════════════');
    console.log('  💰 VibeLab Self-Funding Pipeline v1.0');
    console.log('═══════════════════════════════════════════════\n');

    // Step 1: Submit PR
    const prResult = await submitBountyPR(
        owner, repo, issueNumber, patchCode,
        `fix: auto-resolve issue #${issueNumber} [VibeLab Bounty Hunter]`
    );

    if (prResult.success) {
        console.log(`\n✅ PR submitted: ${prResult.prUrl}`);

        // Step 2: Attempt bounty claim (if Gitcoin configured)
        await claimGitcoinBounty(`${owner}/${repo}#${issueNumber}`);
    }

    // Step 3: Check wallet
    const balance = await checkWalletBalance();

    // Step 4: Auto-purchase if applicable
    if (balance.usd >= AUTO_SPEND_THRESHOLD_USD) {
        await buyApiCredits();
    }

    console.log('\n═══════════════════════════════════════════════');
    console.log('  💰 Funding pipeline complete.');
    console.log('═══════════════════════════════════════════════');

    return { pr: prResult, balance };
}

// ─── CLI Entrypoint ───
if (process.argv[1]?.includes('crypto_funder')) {
    const action = process.argv[2] || 'status';

    (async () => {
        switch (action) {
            case 'status':
                await checkWalletBalance();
                console.log(`\n🐝 Known integrations: GitHub${GITHUB_TOKEN ? ' ✅' : ' ❌'}, Gitcoin${GITCOIN_API_KEY ? ' ✅' : ' ❌'}, Stripe${STRIPE_SECRET_KEY ? ' ✅' : ' ❌'}, Web3${WALLET_PRIVATE_KEY ? ' ✅' : ' ❌'}`);
                break;
            case 'buy':
                await buyApiCredits();
                break;
            case 'bounties':
                await checkReplitBounties();
                break;
            default:
                console.log('Usage: node crypto_funder.js [status|buy|bounties]');
        }
    })();
}
